### PR TITLE
logging: fix typo in connected_to_journal docs

### PR DESCRIPTION
**Pull request by dfreese**

### CODE REVIEW

**Comment by swsnr** [comment]
I don't mind either way, so I'd leave this for @lucab to review.

**Comment by lucab** [comment]
Oh well, this is mostly a matter of taste and styles.
I personally wrote initially this function in the non-functional way that you are now proposing again, but @swsnr preferred the `map_or()` so we settled on that. There is no absolute better form, but the current one avoids early-returns and rightward drift.
In the spirit of not touching code that doesn't need to be fixed, I'd suggest to only address the typo in this PR.

**Comment by dfreese** [comment]
> In the spirit of not touching code that doesn't need to be fixed, I'd suggest to only address the typo in this PR.

Done

**Comment by swsnr** [comment]
Thanks. I allowed myself to merge this right away 😇

**Pull request merged**
