### PR TITLE
Release 0.3.0

### PR DESCRIPTION
**Pull request by lucab**
Changes:
 * activation: do not discard unknown descriptors
 * errors: switch to thiserror
 * logging: properly encode multiline journal messages
 * cargo: refresh all dependencies
 * ci: upgrade to GitHub-native Dependabot
 * ci: bump toolchains
 * ci: move Travis jobs to GitHub actions

### CODE REVIEW

**Comment by lunaryorn** [comment]
🙏🎉

**Comment by lucab** [comment]
Tagged: https://github.com/lucab/libsystemd-rs/releases/tag/v0.3.0
Published: https://crates.io/crates/libsystemd/0.3.0

**Comment by lunaryorn** [comment]
@lucab Thanks a lot for your fast review and even faster release :hugs:

**Pull request merged**
