### PR TITLE
sysusers: add parsing logic

### PR DESCRIPTION
**Pull request by lucab**
This adds support for parsing entries from sysusers.d lines.
Overall logic is organized around the 'nom' parser-combinator
framework.
It is now possible to roundtrip configuration entries, loading
content from files as well as writing back data.

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
(Skimmed) LGTM.

Though are the systemd developers aware of this parser?  Its existence may (likely will) require pull requests here as they evolve the format in the future.

In particular if we end up in a situation where e.g. rpm-ostree starts crashing at build time because a newer systemd package uses a new type tag, I think that's going to be a long term problem.

We can *mostly* mitigate that by having any new sysusers changes done via a PR here and try to respin e.g. rpm-ostree before newer systemd, but longer term I think we're going to need this parser to gracefully handle unknown features.

**Comment by lucab** [comment]
> longer term I think we're going to need this parser to gracefully handle unknown features

I think you raised a fair point. Let's rework the parser here to log a warning and proceed on unrecognized line types.

**Comment by lucab** [comment]
Added one commit to detect&recover on unknown entry types, let me know if that meets your expectations now.

**Comment by lucab** [comment]
@cgwalters unless further comments, I'm going ahead and merging this.

**Review by cgwalters — APPROVED** [review]
Sorry, lost this one in queue, I will try to watch this repo too.

**Pull request merged**
